spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/lunch?serverTimezone=Asia/Seoul&characterEncoding=utf8&autoReconnect=true
    username: root
    password: passwordfortest
  webflux:
    base-path: /api/v2
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
server:
  host: https://e615de3cf95d.ngrok.io
